const Images =[
    {id:1, src:"/portfolio/8.jpg",title:"Baäl", body:"Houtskool op papier, 42 x 59.4 cm"},
    {id:2, src:"/portfolio/9.jpg",title:"The Last",body:" Houtskool op papier, 42 x 59.4 cm"},
    {id:3, src:"/portfolio/10.jpg" ,title:"Zuljin’s end",body:" Houtskool op papier, 42 x 59.4 cm"},
    {id:4, src:"/portfolio/13.jpg",title:"Shoq Sca Beach",body:"Collagetechniek en Acryl op papier, 42 x 29.7 cm"},
    {id:5, src:"/portfolio/14.jpg",title:"Oracilum",body:"Collagetechniek en Acryl op papier, 42 x 29.7 cm"},
    {id:6, src:"/portfolio/16.jpg",title:"Tadhiel",body:"Collagetechniek en Acryl op papier, 210 x 170 cm"},
    {id:7, src:"/portfolio/17.jpg",title:"Dertum’s work",body:"Houtskool en Acryl op mdf, 122 x 66 cm"},
    {id:8, src:"/portfolio/20.jpg",title:"Tantiil",body:"Houtskool en Acryl op mdf, 122 x 66 cm"},
    {id:9, src:"/portfolio/21.jpg",title:"Eluïn",body:"Houtskool en Acryl op mdf, 122 x 66 cm"},
    {id:10, src:"/portfolio/22.jpg",title:"Greed",body:"Houtskool en Acryl op mdf, 122 x 66 cm"},
    {id:11, src:"/portfolio/24.jpg",title:"Ran",body:"Digitaal portret"},
    {id:12, src:"/portfolio/25.jpg",title:"Parsec",body:"Digitaal portret"},
    {id:13, src:"/portfolio/27.png",title:"Calicotherium",body:"Digitaal schilderij"},
    {id:14, src:"/portfolio/28.png",title:"Elasmotherium",body:"Digitaal schilderij"},
    {id:15, src:"/portfolio/31.png",title:"Black Dragon",body:" Digitaal schilderij"},
    {id:16, src:"/portfolio/32.png",title:"Logo",body:"Second Chance Dans groep"},
    {id:17, src:"/portfolio/33.jpg",title:"Logo",body:"The Stages Theater groep"},
    {id:18, src:"/portfolio/37.png",title:"Pin ontwerp",body:""},
    {id:19, src:"/portfolio/38.png",title:"Rhyno beetle",body:"Digitaal schilderij"},
    {id:20, src:"/portfolio/39.png",title:"Longtail Seaturtle",body:"Digitaal schilderij"},
    {id:21, src:"/portfolio/40.png",title:"Killer Wasp",body:"Digitaal schilderij"},
    {id:22, src:"/portfolio/42.png",title:"Ksin Que",body:"Digitaal schilderij"},
    {id:23, src:"/portfolio/43.png",title:"Dotran Bogokh",body:"Digitaal schilderij"},
    {id:24, src:"/portfolio/45.png",title:"Verjaardagskaart hans",body:""},
    {id:25, src:"/portfolio/46.png",title:"Gengar",body:"Digitaal schilderij"},
    {id:26, src:"/portfolio/47.png",title:"Gyrados the Great Wave,",body:"Digitaal schilderij"},
    {id:27, src:"/portfolio/48.png",title:"Pokemon Origen",body:"Digitaal schilderij"},
    {id:28, src:"/portfolio/49.png",title:"Untitled",body:"Digitaal schilderij"},
    {id:29, src:"/portfolio/50.png",title:"Famaly of Bears",body:"Digitaal schilderij"},
    {id:30, src:"/portfolio/51.png",title:"Zuljin",body:" Digitaal schilderij"},
    {id:31, src:"/portfolio/52.png",title:"Panther-rider patrol",body:"Digitaal schilderij"},
    {id:32, src:"/portfolio/53.png",title:"Warrior’s Meet",body:"Digitaal schilderij"},
    {id:33, src:"/portfolio/54.png",title:"Forest Stream",body:"Digitaal schilderij"},
    {id:34, src:"/portfolio/55.png",title:"The Gorge",body:"Digitaal schilderij"},
    {id:35, src:"/portfolio/56.png",title:"Thomas & Sela",body:"Digitaal schilderij"},
    {id:36, src:"/portfolio/57.png",title:"Vulash Archipelago",body:"Digitaal schilderij"},
    {id:37, src:"/portfolio/battle map glowing mushroom cave.jpg",title:"Seacave",body:"Battlemap"},
    {id:38, src:"/portfolio/coastal city 1.jpg",title:"Coastal city",body:"reference map"},
    {id:39, src:"/portfolio/Dryads 1.png",title:"Dryads",body:"monster page"},
    {id:40, src:"/portfolio/Dryads 2.png",title:"Dryads",body:"monster page"}
    


]
export default Images;